### ISSUE TITLE
Consider using FastBroadcast.jl

### ISSUE THREAD

**Issue by ranocha** [JoshuaLampert/DispersiveShallowWater.jl#126]
I have observed that `@..` from [FastBroadcast.jl](https://github.com/YingboMa/FastBroadcast.jl) instead of `Base.@.` can improve the performance. It might be worth trying this out here - at least in the future for models where the elliptic solves do not dominate the runtime.

**Comment by JoshuaLampert** [comment]
Sounds good. I can have a look when I find some time. But, PRs are also welcome of course :smile:

**Comment by ranocha** [comment]
I will look into this when implementing the hyperbolic approximation of the Serre-Green-Naghdi equations
